### ISSUE TITLE
GDL homepage

### ISSUE THREAD

**Issue by pjb7687** [gnudatalanguage/gnudatalanguage.github.io#2]
Since this seems like an empty website, how about migrate the old GDL website on sf.net to here and continue work on it?

The old website can be found here:
https://web.archive.org/web/20180321230732/http://gnudatalanguage.sourceforge.net/index.php

**Comment by slayoo** [comment]
My feeling is that we need something simpler and new that would answer the following key questions:
- how to get an up-to-date GDL running on Windows and OSX (installers, not compilation)
- which functionalities are working
- why there is no documentation and where to look for relevant materials
- how to provide feedback 
- how to cite
- how to try without installation (via Jupyter in the cloud, for instance)
- where we need manpower in development
- screenshots - pictures are worth 1000+ words (people don't know we have widgets, projections, GEOTIFF, Windows support, etc)

Any other information that quickly gets outdated (and we know it always does), should be linked to github where it is either automatically updated or at least has a chance to be updated. Here I mean: requirements, credits, newest release, FAQ (we now have https://github.com/gnudatalanguage/gdl/discussions), 

Thanks for starting the thread!
And any help in making a GDL website finally re-appear: very welcome!
@alaingdl @GillesDuvert any thoughts?

**Comment by GillesDuvert** [comment]
As usual, it's more with having somebody able to spend quite a considerable time to do the job than anything else.
It was mentioned somewhere that it is also important to remove the old places where obsolete information is available.
Having GDL up to date and advertized in the distributions and the pages where scientits publicize IDL procedures (like NASA's idlastro) is IMHO at this time more important than developing a documentation.
For me, GDL's wiki is a good starting point as we can (an I do sometimes) add informations, of course not proper documentation.

**Comment by pjb7687** [comment]
Yes it makes sense to replace the contents with the newer documents. How about the overall appearance, i.e. theme? You can make another one, but actually, I also like the old one.

**Comment by GillesDuvert** [comment]
I agree the old webpage was good-looking!

**Comment by pjb7687** [comment]
Based on the old theme: https://github.com/gnudatalanguage/gnudatalanguage.github.io/pull/3

**Comment by slayoo** [comment]
Thank again @pjb7687 for bringing it back and arranging the wiki-sync mechanism!
BTW, GitHub also offers the magic .github repositories which may contain README.md file that could be shown above repo list on github.com/gnudatalanguage - we could put there links to packages, wiki, website, binaries, etc

As here: https://github.com/atmos-cloud-sim-uj/ (rendered from https://github.com/atmos-cloud-sim-uj/.github/blob/main/profile/README.md)

**Comment by pjb7687** [comment]
It's very good to know that, like this? https://github.com/gnudatalanguage/.github

**Comment by slayoo** [comment]
Thank you, @pjb7687!
